
package ru.vtb.msa.person.wsdl.dataquality;

import org.springframework.beans.factory.annotation.Value;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Person_spcMatch_spcWeb_spcService", targetNamespace = "http://siebel.com/DataQuality", wsdlLocation = "file:/P:/Docs/WSDL/PersonInput%20Match%20Web%20Service.wsdl")
public class PersonSpcMatchSpcWebSpcService
    extends Service
{

    private final static URL PERSONSPCMATCHSPCWEBSPCSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONSPCMATCHSPCWEBSPCSERVICE_EXCEPTION;
    private final static QName PERSONSPCMATCHSPCWEBSPCSERVICE_QNAME = new QName("http://siebel.com/DataQuality", "Person_spcMatch_spcWeb_spcService");

    @Value("${wsdlpath}")
    private static String wsdlpath;

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdlpath);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONSPCMATCHSPCWEBSPCSERVICE_WSDL_LOCATION = url;
        PERSONSPCMATCHSPCWEBSPCSERVICE_EXCEPTION = e;
    }

    public PersonSpcMatchSpcWebSpcService() {
        super(__getWsdlLocation(), PERSONSPCMATCHSPCWEBSPCSERVICE_QNAME);
    }

    public PersonSpcMatchSpcWebSpcService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONSPCMATCHSPCWEBSPCSERVICE_QNAME, features);
    }

    public PersonSpcMatchSpcWebSpcService(URL wsdlLocation) {
        super(wsdlLocation, PERSONSPCMATCHSPCWEBSPCSERVICE_QNAME);
    }

    public PersonSpcMatchSpcWebSpcService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONSPCMATCHSPCWEBSPCSERVICE_QNAME, features);
    }

    public PersonSpcMatchSpcWebSpcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonSpcMatchSpcWebSpcService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonSpcMatch
     */
    @WebEndpoint(name = "Person_spcMatch")
    public PersonSpcMatch getPersonSpcMatch() {
        return super.getPort(new QName("http://siebel.com/DataQuality", "Person_spcMatch"), PersonSpcMatch.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonSpcMatch
     */
    @WebEndpoint(name = "Person_spcMatch")
    public PersonSpcMatch getPersonSpcMatch(WebServiceFeature... features) {
        return super.getPort(new QName("http://siebel.com/DataQuality", "Person_spcMatch"), PersonSpcMatch.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONSPCMATCHSPCWEBSPCSERVICE_EXCEPTION!= null) {
            throw PERSONSPCMATCHSPCWEBSPCSERVICE_EXCEPTION;
        }
        return PERSONSPCMATCHSPCWEBSPCSERVICE_WSDL_LOCATION;
    }

}
