
package ru.vtb.msa.person.wsdl.dataquality;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Person_spcMatch", targetNamespace = "http://siebel.com/DataQuality")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ru.vtb.msa.person.wsdl.dataquality.ObjectFactory.class,
        ru.vtb.msa.person.wsdl.xml.swipersonmatchinputio.ObjectFactory.class,
        ru.vtb.msa.person.wsdl.xml.swipersonmatchoutputio.ObjectFactory.class
})
public interface PersonSpcMatch {


    /**
     * 
     * @param personMatchInput
     * @return
     *     returns com.siebel.dataquality.PersonMatchOutput
     */
    @WebMethod(operationName = "PersonMatch", action = "document/http://siebel.com/DataQuality:PersonMatch")
    @WebResult(name = "PersonMatch_Output", targetNamespace = "http://siebel.com/DataQuality", partName = "PersonMatch_Output")
    public PersonMatchOutput personMatch(
        @WebParam(name = "PersonMatch_Input", targetNamespace = "http://siebel.com/DataQuality", partName = "PersonMatch_Input")
        PersonMatchInput personMatchInput);

}
